//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "Lab7_interrupt.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h" 			// manually added
#include "inc/tm4c123gh6pm.h"					// manually added

//*****************************************************************************
volatile uint32_t count = 0;

void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF0 for GPIOInput (SW1)
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF4 for GPIOInput (SW1)
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF1 for GPIOOutput (RED)
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
		
		//
    // Enable pin PF2 for GPIOOutput (BLUE)
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
		
		// Enable internal pull-up on PF0 and PF4
		GPIO_PORTF_PUR_R |= 0x11;
}

void 
Interrupt_Init(void)
{
	IntEnable(INT_GPIOF); 							// enable interrupt 30 in NVIC (GPIOF) Code: NVIC_EN0_R |= 0x40000000;
	IntPrioritySet(INT_GPIOF, 0x00);		// configure GPIOF interrupt priority as 0: NVIC_PRI7_R &= ~0x00E00000;
	GPIO_PORTF_IM_R |= 0x11;						// arm interrupt on PF0 and PF4
	GPIO_PORTF_IS_R &= ~0x11;						// PF0 and PF4 are edge-sensitive
	GPIO_PORTF_IBE_R &= ~0x11;					// PF0 and PF4 not both edges trigger, depends on IEV register
	GPIO_PORTF_IEV_R &= ~0x11;					// PF0 and PF4 falling edge event
	IntMasterEnable();									// globally enable interrupt  __asm("    cpsie   i\n")
}

//interrupt handler
void GPIOPortF_Handler(void)
{
	//switch debounce
	NVIC_EN0_R &= ~0x40000000;
	SysCtlDelay(53333);					// Delay for a while
	NVIC_EN0_R |= 0x40000000;
	
	//SW1 is pressed (PF4)
	if(GPIO_PORTF_RIS_R&0x10)
	{
		// acknowledge flag for PF4
		GPIOIntClear(GPIO_PORTF_BASE, GPIO_PIN_4);		//GPIO_PORTF_ICR_R |= 0x01; 
		
		//SW2 is pressed
		if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)== 0x00)
		{
			//counter incremented by 1
			count++;
		}
	}
	
	//SW2 is pressed (PF4)
  if(GPIO_PORTF_RIS_R&0x01)
	{
		// acknowledge flag for PF0
		GPIOIntClear(GPIO_PORTF_BASE, GPIO_PIN_0);		//GPIO_PORTF_ICR_R |= 0x01; 
		
		//SW2 is pressed
		if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)== 0x00)
		{
			//counter incremented by 1
			count--;
		}
	}
}

int main(void)
{
	
		//initialize the GPIO ports	
		PortFunctionInit();
		
		//configure the GPIOF interrupt
		Interrupt_Init();
		
//	//Red LED on
//				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIO_PIN_1);
//				//Blue LED on
//				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_PIN_2);
    //
    // Loop forever.
    //
    while(1)
    {
			// if 0th bit is 1 & 1st is 1
			if (((count&0x01)== 0x01 & (count&0x02)== 0x02))
			{
				//Red LED on
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIO_PIN_1);
				//Blue LED on
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_PIN_2);
			}
			
			// if 1st bit is 1 & 0th bit is 0
			else if (((count&0x02)== 0x02 & (count&0x01)== 0x00))
			{
				//Blue LED on
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_PIN_2);
				// Red LED off
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
			}
		
			// if 1st bit is 0 & 0th bit is 1
			else if (((count&0x02)== 0x00 & (count&0x01)== 0x01))
			{
				// Red LED on
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIO_PIN_1);
				//Blue LED off
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
			}
			
			// if 1st & 0th bits are 0
			else	
			{
				// Red LED off
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
				//Blue LED off
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
			}
    }
}
